/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAbout: typeof import('./../components/TheAbout.vue')['default']
    TheContact: typeof import('./../components/TheContact.vue')['default']
    TheEducation: typeof import('./../components/TheEducation.vue')['default']
    TheExperiences: typeof import('./../components/TheExperiences.vue')['default']
    TheHeader: typeof import('./../components/TheHeader.vue')['default']
    TheNav: typeof import('./../components/TheNav.vue')['default']
    TheNavIcon: typeof import('./../components/TheNavIcon.vue')['default']
    TheNavItem: typeof import('./../components/TheNavItem.vue')['default']
    TheNavMobile: typeof import('./../components/TheNavMobile.vue')['default']
    TheProjects: typeof import('./../components/TheProjects.vue')['default']
    TheSection: typeof import('./../components/TheSection.vue')['default']
    TheSkills: typeof import('./../components/TheSkills.vue')['default']
    TheSummary: typeof import('./../components/TheSummary.vue')['default']
    TheTitle: typeof import('./../components/TheTitle.vue')['default']
  }
}
